# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_auto_20171108_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ('id',)},
        ),
    ]
