# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_auto_20171109_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='search_index',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='search_index',
        ),
    ]
